### ISSUE TITLE
Add an MIT license

### ISSUE THREAD

**Issue by mendoc** [gouri-panda/Pig-game#17]
I want to add an MIT license to the project considering the following resource: https://opensource.org/licenses/MIT

**Comment by gouri-panda** [comment]
yes @mendoc sure please go ahead!

**Comment by mendoc** [comment]
Need your name for the license please. I thought of Gouri Panda. Its good ?

**Comment by gouri-panda** [comment]
> Need your name for the license please. I thought of Gouri Panda. Its good ?

Gourishankar panda will be good ;)
