### ISSUE TITLE
Categories images into one folder

### ISSUE THREAD

**Issue by gouri-panda** [gouri-panda/Pig-game#2]
Right now images are in the home folder.move into a separate folder

**Comment by smcveigh941** [comment]
I am working on this :)

**Comment by Sanchit-Trivedi** [comment]
Hi, can you please assign me this issue

**Comment by mgilberties** [comment]
Hi,  I have made a pull request with the changes on for your consideration.

**Comment by gouri-panda** [comment]
> I am working on this :)

As @smcveigh941 first considered he should resolve this issue

**Comment by gouri-panda** [comment]
@mgilberties should check out this <p><a href="https://hacktoberfest.digitalocean.com?wvideo=rrnq2hxoso"><img src="https://embed-fastly.wistia.com/deliveries/49bd387c40e2c5aada92abdf973bc46d.jpg?image_play_button_size=2x&amp;image_crop_resized=960x540&amp;image_play_button=1&amp;image_play_button_color=1e71e7e0" width="400" height="225" style="width: 400px; height: 225px;"></a></p><p><a href="https://hacktoberfest.digitalocean.com?wvideo=rrnq2hxoso">Hacktoberfest presented by DigitalOcean</a></p>

**Comment by smcveigh941** [comment]
Hey @gouri-panda, please see my PR :)
