### ISSUE TITLE
Save the user's theme choice

### ISSUE THREAD

**Issue by mendoc** [gouri-panda/Pig-game#22]
When you choose the theme in dark mode, the app does not keep it after refreshing the page. I want to save the user's choice in cookies.

**Comment by gouri-panda** [comment]
@mendoc that would be great! store in the localpref.

**Comment by mendoc** [comment]
Ok. I will use local storage for that.

**Comment by umairayub79** [comment]
@gouri-panda I did that check PR #28

**Comment by gouri-panda** [comment]
@umairayub79 #22 was assigned to @mendoc . You can raise a new issue and start solving it now.

**Comment by umairayub79** [comment]
@gouri-panda our solutions are different pick whatever you like

**Comment by mendoc** [comment]
@gouri-panda can you merge my PR #29 if all is good ?
