### ISSUE TITLE
Create a logo for Pig-game app

### ISSUE THREAD

**Issue by gouri-panda** [gouri-panda/Pig-game#24]
A simple and plain logo for the app.

**Comment by umairayub79** [comment]
![Untitled](https://user-images.githubusercontent.com/46655787/95026951-5a0fe780-06ae-11eb-8820-556a7e84bd71.png)

**Comment by gouri-panda** [comment]
@umairayub79 It should connect with the app's behavior with the logo.

**Comment by lucid-dreem** [comment]
I created a pull request for a potential logo... feel free to use it if it fits the theme
