### ISSUE TITLE
Add screenshot of web app in readme file

### ISSUE THREAD

**Issue by gouri-panda** [gouri-panda/Pig-game#3]
Play with the game a little bit and add proper screenshots of the file in the `readme` file

**Comment by hauze-v** [comment]
Hi there, I can do this for you if you will assign to me.

**Comment by Sanchit-Trivedi** [comment]
Hi, I would like to take this up

**Comment by gouri-panda** [comment]
@hauze-v  and @Sanchit-Trivedi  Consider your self assigned. You should put 2 perfect photos of the website in the PR.

**Comment by hauze-v** [comment]
@gouri-panda If you like the screenshot and end up merging, would you mind opting-in to Hactoberfest? It looks like my PR is ineligible. Here's what Digital Ocean says:


Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.

**Comment by gouri-panda** [comment]
> @gouri-panda If you like the screenshot and end up merging, would you mind opting-in to Hactoberfest? It looks like my PR is ineligible. Here's what Digital Ocean says:
> 
> Ineligible Repository
> Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.

@hauze-v Now you are good to go.
