### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ghost** [gouri-panda/Pig-game#30]
Hey panda, I noticed a copyright watermark, however, I could not find an actual license. Would you consider giving this project a license? Like MIT?

**Comment by gouri-panda** [comment]
sure add a license. go for it.

**Comment by ghost** [comment]
On It.

**Comment by ghost** [comment]
I noticed that the code has a MIT licence however its not written in the readme.md. Im just going to submit another PR with the title "MIT" in the readme
