### ISSUE TITLE
Wrong style comments added in HTML reflect on the site

### ISSUE THREAD

**Issue by amoghrajesh** [gouri-panda/Pig-game#42]
![image](https://user-images.githubusercontent.com/35884252/95094588-b1ae6180-0747-11eb-906e-d32c4a2f4da8.png)

**Comment by amoghrajesh** [comment]
Assign this small issue to me, I can fix it @gouri-panda

**Comment by gouri-panda** [comment]
@amoghrajesh please go ahead!
