### ISSUE TITLE
Show rules for news players

### ISSUE THREAD

**Issue by mendoc** [gouri-panda/Pig-game#52]
It will be useful to have an button that shows rules for new players.

I want to work on.

**Comment by gouri-panda** [comment]
@mendoc sure go ahead!

**Comment by mendoc** [comment]
@gouri-panda I finished ! Take a look when possible.

**Comment by mendoc** [comment]
Please @gouri-panda , 

May you install Slack on your Github to allow me to be notified for Pig-game activity ?

Bellow, the link to do that.
https://slack.github.com/github/install/43576162/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0cmlnZ2VyX2lkIjoiMTQxODk3ODMyNzg0NC44NzMzNTUzMTUwNjIuNTg1MTgwNWJhMDE3NjE4Y2RkYjJhNThiMGE5ODg3MjMiLCJyZXBsYXlTbGFzaENvbW1hbmQiOnRydWUsInRlYW1TbGFja0lkIjoiVFJQQUY5OTFVIiwidXNlclNsYWNrSWQiOiJVUlVMRTJCTkQiLCJjaGFubmVsU2xhY2tJZCI6IkMwMUNNR0IzTk02IiwiaWF0IjoxNjAyMDc4NjMwLCJleHAiOjE2MDIwODIyMzB9.9ugSfmrMid17LJEhUEwBQBS5QxQDQVB63EDRUzi4SVk

**Comment by gouri-panda** [comment]
@mendoc I will do that until than you can watch the repository by github watch.Thanks.

**Comment by gouri-panda** [comment]
@mendoc Please join our [slack](https://join.slack.com/t/newworkspace-uco4265/shared_invite/zt-huokfrna-unLOpo_bo7fKACHZ2rH7jA) channel.

**Comment by inglorious-ratbastard** [comment]
Working on this issue but dark mode theme is incomplete on modal.
