### ISSUE TITLE
Roll two dice

### ISSUE THREAD

**Issue by gouri-panda** [gouri-panda/Pig-game#64]
It will be more fun if we add two dice.

**Comment by christopherwalkerml** [comment]
I can probably take this one, but can I get more info? Thanks!

**Comment by NicholasACTran** [comment]
Can I take this ticket? I have the info needed to execute

**Comment by gouri-panda** [comment]
Sure go ahead!

**Comment by Aditya489** [comment]
hi, can you assign me this? thanks

**Comment by NicholasACTran** [comment]
@Aditya489 This is already completed in a PR
