### ISSUE TITLE
Fix double roll implementation

### ISSUE THREAD

**Issue by zoltanszopory-tw** [gouri-panda/Pig-game#79]
[According to wikipedia](https://en.wikipedia.org/wiki/Pig_(dice_game)): "If a double is rolled, the point total is added to the turn total as with any roll but the player is obligated to roll again (possible sub-variation of the two-dice game)"

**Comment by NicholasACTran** [comment]
This would be an interesting rule to implement, are you interested in taking up the issue?

**Comment by mabhay3420** [comment]
* Need to implement the double dice rule
    * store the last two values of dice.
    * if they are both 6
        - disable the hold button
    * keep the hold button disabled until a number different than 6 comes out.
    * else continue as usual

* To implement this
    * In case we roll two dice, this should be one by one 
        * to determine whether it is a double roll that spans across two double rolls
    * If we get 1 at any point, we should just set the score to 0 and give a chance to the next player

**Comment by mabhay3420** [comment]
This involves changing the behavior of double rolls, and in case someone tries to implement a 3 or 4 roll variant, he/she needs to keep in mind that the rolls are one by one. Let me know if there are any suggestions regarding this.
