### ISSUE TITLE
App should show  highest score

### ISSUE THREAD

**Issue by gouri-panda** [gouri-panda/Pig-game#8]
When the game finishes or the current score is greater than the highest score then the web app should show the highest score.

**Comment by mendoc** [comment]
I can help here...

**Comment by gouri-panda** [comment]
@mendoc sure go ahead!

**Comment by symtalha14** [comment]
Hello,
I would love to contribute to it. Please assign me  this issue.

**Comment by gouri-panda** [comment]
@symtalha14 Thank you for interesting with this issue @mendoc is working with this issue.

**Comment by mendoc** [comment]
I think this issue can be closed.
