### ISSUE TITLE
Add dark theme in app

### ISSUE THREAD

**Issue by gouri-panda** [gouri-panda/Pig-game#9]
Right now we have only a light theme. In order to. improve the user experience we should add both a dark theme and a light theme.
* Expected behavior
Users can select both a light theme or dark theme by a toggle switch

**Comment by PhilippeBarre** [comment]
Hello, I can do it, can you asign me please ?
Best regards

**Comment by gouri-panda** [comment]
@PhilippeBarre go ahead!

**Comment by thinkswell** [comment]
Hello, I can help to do it, you can assign me for the task.
Thank You.

**Comment by PhilippeBarre** [comment]
Hello @thinkswell , I'm already on it ;)

**Comment by thinkswell** [comment]
Okay, No problem. :) 👍
